app/video_storage/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from uploader.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/uploader/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import PROTECT


class Record(models.Model):
    objects = models.Manager()

    NEW_FILE = 0
    NEW_LINK = 1
    MAKING_PREVIEW = 3
    CONVERTING_MP4 = 4
    CONVERTING_WEBM = 5
    READY = 6
    ERROR = 999

    MP4 = 'mp4'
    WEBM = 'webm'

    STATUS_CHOICES = [
        (NEW_FILE, 'New video file'),
        (NEW_LINK, 'New video link'),
        (MAKING_PREVIEW, 'Making preview'),
        (CONVERTING_MP4, 'Converting to mp4'),
        (CONVERTING_WEBM, 'Converting to webm'),
        (READY, 'Ready'),
        (ERROR, 'Error'),
    ]
    RESULT_FORMATS = {
        CONVERTING_MP4: MP4,
        CONVERTING_WEBM: WEBM,
    }

    NEXT_STEPS = {
        NEW_LINK: MAKING_PREVIEW,
        NEW_FILE: MAKING_PREVIEW,
        MAKING_PREVIEW: CONVERTING_MP4,
        CONVERTING_MP4: CONVERTING_WEBM,
        CONVERTING_WEBM: READY
    }

    class Meta:
        verbose_name_plural = 'Загруженные видео'

    name = models.CharField(max_length=2000, verbose_name='имя файла', null=True, blank=True)
    upload_time = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')
    upload_by = models.ForeignKey(User, verbose_name='Кем добавлен', null=True, blank=True, on_delete=PROTECT)
    process_status = models.IntegerField(choices=STATUS_CHOICES, verbose_name='Статус обработки')

    def __str__(self):
        return self.name


class RecordFiles(models.Model):
    objects = models.Manager()

    PREVIEW = 0
    CONVERTED_VIDEO = 1

    FILE_TYPE_CHOICES = [
        (PREVIEW, 'Preview image file'),
        (CONVERTED_VIDEO, 'Converted video file'),
    ]

    record = models.ForeignKey(Record, verbose_name='Запись пользователя', null=True, blank=True, on_delete=PROTECT)
    file_type = models.IntegerField(choices=FILE_TYPE_CHOICES, default=PREVIEW, verbose_name='Тип файла')
    file_format = models.FileField(blank=True, null=True, verbose_name='Расширение')
    file = models.FileField(blank=True, null=True, verbose_name='Файл')

app/uploader/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView

from .models import Record, RecordFiles
from .tasks import handle_video, get_name_from_url, SourceFileSaver


class IndexView(DetailView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        all_records = Record.objects.all().order_by('-upload_time')
        video_list = []
        for video in all_records:
            record_files = RecordFiles.objects.filter(record=video).all()
            video_list.append({
                'video': video,
                'preview': record_files.filter(file_type=RecordFiles.PREVIEW).first(),
                'video_file_mp4': record_files.filter(file_format=Record.MP4).first(),
                'video_file_webm': record_files.filter(file_format=Record.WEBM).first()
            })

        return {'video_list': video_list}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, *args, **kwargs):
        video_file = request.FILES.get('video')
        video_link = request.POST.get('link')
        req_user = None if self.request.user.is_anonymous else request.user

        if video_file:
            obj = Record.objects.create(name=video_file.name, process_status=Record.NEW_FILE, upload_by=req_user)

            # save file on disk before process in different container
            saver = SourceFileSaver(obj.id, video_file.temporary_file_path(), video_file.name)
            saved_file_path = saver.process()

            _ = handle_video.delay(obj.id, video_file.name, saved_file_path)

        elif video_link:
            video_name = get_name_from_url(video_link)
            obj = Record.objects.create(name=video_name, process_status=Record.NEW_LINK, upload_by=req_user)
            _ = handle_video.delay(obj.id, video_name, video_link)

        return redirect('index')

app/uploader/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row m-b-lg">

        </div>
        <div class="row m-b-lg justify-content-center">
            <div class="col-lg-10">
                <form action="{% url 'index' %}" method="post" enctype="multipart/form-data">
                    <div class="input-group" id="file_input_group">
                         {% csrf_token %}
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="customFile" name="video">
                            <label class="custom-file-label" for="customFile">Выбрать файл</label>
                        </div>
                        <span class="input-group-append">
                            <button type="submit" class="btn btn-primary1">Загрузить</button>
                        </span>
                    </div>
                    <div class="input-group" id="link_input_group" style="display: none;">
                        <div class="custom-file">
                            <input type="text" class="form-control" name="link">
                        </div>
                        <span class="input-group-append">
                            <button type="submit" class="btn btn-primary1">Загрузить</button>
                        </span>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1"
                               value="video_file_input" checked>
                        <label class="form-check-label" for="inlineRadio1">Файл</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2"
                               value="option2">
                        <label class="form-check-label" for="inlineRadio2">Ссылка</label>
                    </div>
                </form>
            </div>
        </div>

                <div class="row m-b-lg justify-content-center">
                    <div class="col-lg-10">
                        <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Мои файлы</h5>
                    </div>
                    <div class="ibox-content">
                        <table class="table borderless">
                            <tbody>
                               {% for row in video_list  %}
                                <tr>
                                    <td>
                                        {% if row.video.process_status == 6 %}
                                            <div align="left" class="embed-responsive embed-responsive-16by9" style="width: 500px">
                                                <video controls class="embed-responsive-item">
                                                    <source src="{{ row.video_file_mp4.file.url }}" type="video/mp4">
                                                    <source src="{{ row.video_file_webm.file.url }}" type="video/webm">
                                                </video>
                                            </div>
                                        {% elif row.preview %}
                                           <img src="{{ row.preview.file.url }}" class="img-fluid" style="max-width: 500px">
                                        {% else %}
                                            <img src="{% static 'default_video.png' %}" class="img-fluid" style="width: 500px">
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="{{ rows.video.name }}">{{ row.video.name }}</a><br>
                                        {{ row.video.get_process_status_display }}<br>
                                        {{ row.video.upload_time|date:'Y-m-d H:i' }}<br>
                                    </td>
                                </tr>
                              {% endfor %}
                           </tbody>
                        </table>
                    </div>
                </div>
                    </div>
                </div>

    </div>

{% endblock %}

app/uploader/templates/layout.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stepik Video Storage</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'style.css' %}" rel="stylesheet">

    {% block style %}
    {% endblock %}
</head>

<body id="page-top" class="landing-page no-skin-config pace-done">
<div id="inSlider" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Stepik VS
                    </h1>
                    <p>Ваш видео архив</p>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back one"></div>
        </div>

    </div>
</div>
{% block content %}


{% endblock %}
</body>


<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
<script>
    $(document).ready(function () {
  bsCustomFileInput.init()
})

$(document).on('change', 'input:radio', function (event) {
    var radio_id = $(this).attr('id');
    if (radio_id == 'inlineRadio2') {
        $('#link_input_group').show()
        $('#file_input_group').hide()
    }
    else {
        $('#link_input_group').hide()
        $('#file_input_group').show()
    }

});
</script>

</html>